name : Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron : 30 02 * * * #8:AM IST
    - cron : 00 14 * * * #7:30:PM IST
    - cron : 00 06 * * 1-5 # 11:30 IST Monday to driday

jobs:
  run-psotman-tests:
    runs-on: ubuntu-latest

    steps:
    
      - name: checkout the code
        uses: actions/checkout@v6-beta
       
      - name: install nodejs and npm
        uses: actions/setup-node@v6.0.0
        with:
          node-version: '22'


      - name: install newman and htmlexra globally
        run: |
             npm install -g newman
             npm install newman-reporter-htmlextra

      - name: Run the postman collection with newman
        run: |
             newman run 'Inwarrnty-flow collection Copy.postman_collection.json' /
             -e QA.postman_environment.json /
             -r cli,htmlextra

      - name: newman report
        if: always() # its ensure the archive section going to be executed wehther prevous steps failed 
        uses: actions/download-artifact@v6.0.0
        with:
          name: newman report
          path: newman/*.html
          
       
       
             
        
        
        
        
      
      

  

